### ISSUE TITLE
[Feature Request] Option to exclude certain dimensions in the tab list

### ISSUE THREAD

**Issue by IchHabeHunger54** [Crimix/ServerTabInfo#15]
In my pack, the nether is inaccessible, so I would appreciate a config option to blacklist certain dimensions from the tab list.

**Comment by Crimix** [comment]
Sounds like a good feature to add. 
Which Minecraft version is your modpack for?

**Comment by IchHabeHunger54** [comment]
1.16.5

**Comment by IchHabeHunger54** [comment]
Sorry if this is annoying, but is there any progress on this?

**Comment by Crimix** [comment]
Sorry for the slow progress I have not had the time to look into it yet.

**Comment by Crimix** [comment]
I will be backporting it to 1.16.5 now
