### ISSUE TITLE
[Feature Request-1.16.5] Customizable world name

### ISSUE THREAD

**Issue by EnterFor** [Crimix/ServerTabInfo#17]
Hello, I am a Chinese player.
Can I add the ability to customize world names?
I don't know if you understand, BUT I use Google Translate.

**Comment by EnterFor** [comment]
For example, "Overworld," I want to display as "survival world"

**Comment by Crimix** [comment]
This is already possible via resource packs
<img src="https://user-images.githubusercontent.com/7978180/147062973-e626296d-8623-4a51-8b09-f0ba4c40677b.PNG" width="500">

You can just add the following resource pack demo I made
[EnterForDemo.zip](https://github.com/Crimix/ServerTabInfo/files/7761278/EnterForDemo.zip)
