### ISSUE TITLE
Minecraft version 1.20.1 ServerTabInfo-1.20-1.3.8.jar Dimensions not listed

### ISSUE THREAD

**Issue by litjohn50** [Crimix/ServerTabInfo#18]
Mod info ServerTabInfo-1.20-1.3.8.jar
MC version: 1.20.1

Issue: When pressing tab on the game it replaces the vanilla scoreboard, but does not post the current dimension or tps. It just has (Uknown) by the name instead.

**Comment by Crimix** [comment]
Is the mod installed on the server also?

**Comment by Crimix** [comment]
I have just tested on Forge 47.0.35.
There is no issue for me, thus this bug is unconfirmed
