### ISSUE TITLE
[1.16.1] Crashes on servers

### ISSUE THREAD

**Issue by NillerMedDild** [Crimix/ServerTabInfo#7]
Client-side stuff used on server: https://gist.github.com/NillerMedDild/85e4cd455c156ba0801fa36005ac6d67

`ServerTabInfo-1.16.1-1.3.0`

**Comment by Crimix** [comment]
Thank you, I will look into this ASAP

**Comment by Crimix** [comment]
This has now been fixed and a new version is under review on CurseForge.
I also found some other server related issues, these have also been fixed.

Again thank you for reporting this issue 👍

**Comment by NillerMedDild** [comment]
Sure thing, thanks for the quick fix :)
