### ISSUE TITLE
Admin only mode

### ISSUE THREAD

**Issue by Crimix** [Crimix/ServerTabInfo#9]
A server side setting such that only ops are allowed to look at the tps menu. and the dimensions+tps menu should not be displayed in the player tab.
As some players apparently will go on a tps witch hunt (as Communos says [here](https://www.curseforge.com/minecraft/mc-mods/server-tab-info?comment=58)). 

- [x] Implement server config option
- [x] Add op packet (Not needed)
- [x] Remove a column from player tab if not op and config option is on
- [x] Block access to tps page if not op and config option is on

**Comment by VADemon** [comment]
There're "other" client-side mods that can calculate TPS. For admins it'd be a better option to have permissions integration.

**Comment by Crimix** [comment]
> There're "other" client-side mods that can calculate TPS. For admins it'd be a better option to have permissions integration.

Which "other" client side mods without a server side component can calculate the TPS if I might ask. 

What do you mean by permissions integration, is that a mod?

**Comment by Crimix** [comment]
Fixed in 1.3.3 for 1.16.4 as it is hard to limit the versions people already use.
It is enough that players have op level 1.

**Comment by VADemon** [comment]
> What do you mean by permissions integration, is that a mod?

Bukkit servers have a Permissions system, FTB iirc recreated it for Forge mods in one of their utility/integral mods (maybe FTB Utilities). And THEN, if I recall correctly, there's a separate sort of config-like system for FTB mods where servers can push config to clients.

If I were an admin, it'd be nice to see that integration, without the requirement to give people OP. I recall now some mods like Schematica have their server-side plugins that send "disallowed" client features configuration via the plugin channel.

**Comment by Crimix** [comment]
> > What do you mean by permissions integration, is that a mod?
> 
> Bukkit servers have a Permissions system, FTB iirc recreated it for Forge mods in one of their utility/integral mods (maybe FTB Utilities). And THEN, if I recall correctly, there's a separate sort of config-like system for FTB mods where servers can push config to clients.
> 
> If I were an admin, it'd be nice to see that integration, without the requirement to give people OP. I recall now some mods like Schematica have their server-side plugins that send "disallowed" client features configuration via the plugin channel.

I see, I might look into it the FTB thing. The push config to clients is a standard forge thing and I already make use of it to toggle this feature on.
My implementation give people of level 1 op access to it for now if enabled in the config. Ops of this level only bypass spawn protection, unless other mods adds commands which only requires level 1.
